[package]
name = "operation_app"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tokio-tungstenite = "0.24.0"
uuid = { version = "1.10.0", features = ["v4"] }

sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio", "time"] }
chrono = "0.4.38"
strum = "0.26.3"
strum_macros = "0.26.4"
